modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/MC-U-Team/Enhanced-Anvil/issues"
displayURL="https://u-team.info/mods/enhancedanvil"
logoFile="logo.png"
license="Apache-2.0 License"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="enhancedanvil"
	version="${file.jarVersion}"
	displayName="Enhanced Anvil"
	updateJSONURL="https://api.u-team.info/update/enhancedanvil.json"
	description="This mod adds a new anvil to the game that removes the 'Too Expensive' limit restriction but is still not overpowered."
	
	[[dependencies.enhancedanvil]]
	    modId="forge"
	    mandatory=true
	    versionRange="[36.1.12,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.enhancedanvil]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.5]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.enhancedanvil]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.2.1.195,)"
	    ordering="NONE"
	    side="BOTH"