modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MC-U-Team/Enhanced-Anvil/issues"
displayURL="https://u-team.info/mods/enhancedanvil"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="enhancedanvil"
	version="${file.jarVersion}"
	displayName="Enhanced Anvil"
	updateJSONURL="https://api.u-team.info/update/enhancedanvil.json"
	description="This mod adds a new anvil to the game that remove some enchantment restrictions but is still not overpowered."
	
	[[dependencies.enhancedanvil]]
	    modId="forge"
	    mandatory=true
	    versionRange="[31.2.30,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.enhancedanvil]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.15.2]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.enhancedanvil]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.0.0.160,)"
	    ordering="NONE"
	    side="BOTH"